config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :lands, only: [ :new, :create, :show, :index, :edit, :update, :destroy] do

    resources :bookings, only: [ :new, :create, :show ]
  end

  resources :bookings do
    resources :reviews, only: [ :new, :create ]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :land
  has_many :reviews, dependent: :destroy
end

app/models/land.rb
class Land < ApplicationRecord
  belongs_to :user
  has_many :bookings , dependent: :destroy
  has_many :reviews , through: :bookings
  mount_uploader :photo, PhotoUploader

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?


  include PgSearch
  pg_search_scope :search_by_title_and_address,
    against: [ :title, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, numericality: { only_integer: true }, inclusion: { in: (1.. 5).to_a }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :lands
  has_many :bookings
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
   before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

   # Pundit: white-list approach.
   after_action :verify_authorized, except: :index, unless: :skip_pundit?
   after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

   # Uncomment when you *really understand* Pundit!
   # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
   # def user_not_authorized
   #   flash[:alert] = "You are not authorized to perform this action."
   #   redirect_to(root_path)
   def configure_permitted_parameters

    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo, :photo_cache])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :photo, :phone_number])


  end

  private

  def skip_pundit?
   devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
 end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @land = Land.find(params[:land_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @land = Land.find(params[:land_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.land = @land
    # raise
    authorize @booking
    if @booking.save
      redirect_to land_booking_path(@land, @booking)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end




end

app/controllers/lands_controller.rb
class LandsController < ApplicationController

  def index

    if params[:query].present?
      @lands = policy_scope(Land.search_by_title_and_address(params[:query]))
      # @lands_geo = Land.search_by_title_and_address(params[:query]).where.not(latitude: nil, longitude: nil)
      @lands_geo = @lands.where.not(latitude: nil, longitude: nil)
    else
      @lands = policy_scope(Land)
    # raise
    @lands_geo = Land.where.not(latitude: nil, longitude: nil)
    end

    @markers = @lands_geo.map do |land|
     {
       lat: land.latitude,
       lng: land.longitude,
       title: land.title,
       label: "#{land.price}€",
       id: land.id,
       #,
       # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
     }
    end
  end






   def show
    @land = Land.find(params[:id])
    authorize @land
    # @land_geo = @land.where.not(latitude: nil, longitude: nil)
    @markers = [
     {
      lat: @land.latitude,
      lng: @land.longitude,
      title: @land.title,
      label: "#{@land.price}€",
             #,
             # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
     }]
     sum = 0
     @land.reviews.each do |review|
      sum = sum + review.rating
     end
     if @land.reviews.length > 0
      @moyenne = " Average rating: #{sum / (@land.reviews.length)}/5"
    else
      @moyenne = "Waiting for rating"
    end

  end

    def new
      @land = Land.new
      authorize @land
    end

    def create
    # raise
    @land = Land.new(land_params)
    @land.user = current_user
    authorize @land

    if @land.save
      redirect_to land_path(@land)
    else
      render :new
    end
  end

  def edit
    @land = Land.find(params[:id])
    authorize @land
  end

  def update
    # raise
    @land = Land.find(params[:id])
    authorize @land

    if @land.update(land_params)
      redirect_to land_path(@land)
    else
      render :new
    end


  end
  def destroy
    @land = Land.find(params[:id])
    authorize @land
    @land.destroy
    redirect_to lands_path
  end


  private

  def land_params
    params.require(:land).permit(:title, :description, :address, :price, :surface, :photo)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

 def new
    # we need @land in our `simple_form_for`
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @land = @booking.land
    # we need `booking_id` to asssociate review with corresponding booking
    @review.booking = @booking
    authorize @review
    if @review.save
      redirect_to land_path(@land)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">

  <div class="col-xs-12 col-sm-6 col-sm-offset-3 ">
    <br>
    <br>
    <br>
    <%=  simple_form_for [@land, @booking] do |f| %>

    <div >
      <label class="date optional" for="booking_start_date">Date de début</label>
    </div>
    <div >
      <input type="date" id="booking_start_date" name="booking[start_date]">
    </div>
    <br>
    <div >
      <label class="date optional" for="booking_end_date">Date de fin</label>
    </div>
    <div>
      <input type="date" id="booking_end_date" name="booking[end_date]">
    </div>
    <br>
    <div> <%= f.button :button, "RESERVER", type: :submit, class: :'btn btn-treehouse btn-sm' %>
    </div>
    <% end %>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
  </div>
</div>

app/views/bookings/show.html.erb
<html>
<head>

</head>
<body>
  <div class=container>
    <div class=row>
      <div class="text-center">
        <h2>Booking confirmed !</h2>
        <p>Here is the detail of your booking :</p>
      </div>
    </div>

    <div class=row>
      <div class="col-xs-12 col-sm-offset-3 col-sm-6">
        <div class="card card-booking">
          <ul>
            <li><strong>Start Date :</strong> <%= @booking.start_date %></li>
            <br>
            <li><strong>End Date :</strong> <%= @booking.end_date %></li>
            <br>
            <li><strong>Price per night :</strong> <%= @booking.land.price %> €</li>
            <br>
            <li><strong>Total Price :</strong> <%= (@booking.land.price * (@booking.end_date - @booking.start_date)).to_i %> €</li>
            <br>
            <li><strong>Landlord :</strong> <%= @booking.user.email %></li>
            <br>
            <li><strong>Address :</strong> <%= @booking.land.address %></li>
          </ul>
        </div>
      </div>
      <br>
      <div class=row>
        <div class="col-xs-12 col-sm-offset-3 col-sm-6">
          <div class="text-center">
            <%= link_to "Back to the list", lands_path, class:"btn btn-medium" %>
            <%= link_to "Add a Review", new_booking_review_path(@booking), class:"btn btn-treehouse" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/lands/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-3">
      <%= simple_form_for(@land) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.label :price %>
      <%= f.text_field :price %>

      <%= f.label :surface %>
      <%= f.text_field :surface %>

      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>

      <%= f.submit %>
      <% end %>

    </div>
  </div>
</div>

app/views/lands/index.html.erb
<div class="container">
  <div class="main-container">
    <div class="card-container">
      <div class="row">
        <% @lands.each do |land| %>
        <div class="col-xs-12 col-sm-6">
          <% if land.photo_url %>
          <div class="card">
            <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path land.photo %>');">
              <div class="card-description"><h2><%= link_to land.title, land_path(land) %></h2></div>
              <% if land.user.photo_url %>
                <%= cl_image_tag land.user.photo_url, class: "card-user" %>
              <% else %>
               <%= image_tag "logo_airlnp.png", alt:"logo", class:"card-user"%>
               <% end %>
            </div>
            <div class="card-footer">
              <p><%= land.description %> </p>
              <p><%= land.price %>€/night</p>
            </div>
            <!-- <a class="card-link" href="#" ></a> -->
          </div>
          <% else %>
          <div class="card">
            <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">
              <div class="card-description"><h2><%= link_to land.title, land_path(land) %></h2></div>
              <%= image_tag "logo_airlnp.png", alt:"logo", class:"card-user"%>
            </div>
            <div class="card-footer">
              <p><%= land.description %> </p>
              <p><%= land.price %>€/night</p>
            </div>
            <!-- <a class="card-link" href="#" ></a> -->
          </div>
          <% end %>

        </div>
        <% end %>
      </div>
    </div>
    <div class="map-container">
      <div
      id="map"
      style="width: 95%;
      height: 500px;"
      data-markers="<%= @markers.to_json %>"
      ></div>
    </div>
  </div>
</div>
</div>

app/views/lands/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4 ">
      <%= simple_form_for(@land) do |f| %>

      <%= f.input :title, placeholder: 'ex : un joli jardin', input_html:{class:'my_input'}%>
      <%= f.input :description, placeholder: 'Options, équipements ...', input_html:{class:'my_input'}%>
      <%= f.input :address, placeholder: '50 rue de Paradis Marseille', input_html:{class:'my_input'}%>
      <%= f.input :price, placeholder: '€', input_html:{class:'my_input'}%>
      <%= f.input :surface, placeholder: 'm2', input_html:{class:'my_input'}%>
      <%= f.input :photo, input_html:{class:'my_input'}%>
      <%= f.input :photo_cache, as: :hidden %>

      <%= f.button :button, "Partagez", type: :submit, class: :'btn btn-treehouse btn-sm' %>
      <% end %>

    </div>
  </div>
</div>

app/views/lands/shared/_card.html.erb
<div class="container">
  <div class="row">

    <div class="col-xs-12 col-sm-offset-3 col-sm-6">
      <div class="card-show">
        <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @land.photo, crop: :fill%>');"">
         <div class="card-category"> </div>
         <div class="card-description"><h2><%= @land.title %></h2></div>
         <%= cl_image_tag @land.user.photo_url, class: "card-user" %>
       </div>
       <div class="card-footer">
        <p><%= @land.address%> </p>
        <p><%= @land.description %> </p>
        <p><%= @land.price %>€/night</p>
      </div>
      <!-- <a class="card-link" href="#" ></a> -->
    </div>
  </div>

</div>
</div>

app/views/lands/show.html.erb
<div class="main-container">
  <div class="review-container">
    <div class="card-show" >
      <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @land.photo, crop: :fill%>');"">
        <div class="card-category">
          <%= @moyenne %>
        </div>
        <div class="card-description">
          <h2><%= @land.title %></h2>
        </div>
        <%= cl_image_tag @land.user.photo_url, class: "card-user" %>
      </div>

      <div class="card-footer">
       <p><%= @land.address%> </p>
       <p><%= @land.description %> </p>
       <p><%= @land.price %>€/night</p>
      </div>
    </div>
     <!-- <a class="card-link" href="#" ></a> -->
     <div class="review">
      <!-- <div class="card-review"> -->
        <% if @land.reviews.blank? %> Be the first to leave a review
        <% else %>
        <ul>
          <% @land.reviews.each do |review| %>
          <li> <em> <%= review.booking.user.first_name %><em>  <%= ":"%>
           <%= "'"%>  <%=review.content%>   <%="'"%> <%= "🌲" * review.rating%>
         </li>
         <% end %>
       </ul>
       <% end %>
   <!-- </div> -->
 </div>


</div>


<div class="mapandbtn">


 <div
 id="map"
 style="width: 100%;
 height: 60vh;"
 data-markers="<%= @markers.to_json %>"
 ></div>
 <div class="bouton-show">
  <%= link_to "Book this land", new_land_booking_path(@land), class: "btn btn-treehouse" %>
  <%= link_to "Back to the list", lands_path ,class: "btn btn-medium" %>
  <% if @land.user == current_user %>
  <%=link_to "Edit the land", edit_land_path, class: "btn btn-medium"%>

  <%= link_to 'Delete',land_path(@land),
  method: :delete,
  data: { confirm: 'Are you sure?' },class: "btn btn-medium" %>
  <%end %>

</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>TODO</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <!-- <%#= stylesheet_pack_tag 'application', media: 'all' %> Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>

  <%= render 'partials/navbar' %>

  <%= render 'partials/flashes' %>

  <%= yield %>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_pack_tag 'application' %>
  <%= javascript_pack_tag 'map' %>

  <%= render 'partials/footer' %>

</body>
</html>

app/views/pages/home.html.erb
<!-- <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> -->
<html>
  <head>
    <link rel="stylesheets" href="avatar.scss">

  </head>
  <body>

  <%= render 'partials/banner' %>


<!--     <div class="text-center">
      <h2>Pour une journée ou une saison</h2>
      <p>Trouver votre terrain pour un potager, un evenement, un stantionnement ou bien camper! </p>
    </div> -->


  </body>
</html>

app/views/partials/_banner.html.erb
<!--  style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://www.phototeam-nature.com/wp-content/uploads/2015/04/COUV-Islande-85-6.jpg');"> -->
<div class="banner">
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag "event.jpeg" %>
        <div class="carousel-caption">
         <h1>AirLnP</h1>
         <h4>Trouver votre terrain pour un evenement</h4>
         <div class="banner-content">
          <a href="/lands" class="btn-treehouse btn-sm">Trouver un terrain !</a>
          <a href="lands/new" class="btn-treehouse btn-sm"">Louer votre terrain </a>
        </div>
      </div>
    </div>
    <div class="item">
     <%= image_tag "potager.jpg" %>
     <div class="carousel-caption">
       <h1>AirLnP</h1>
       <h4>Trouver votre terrain pour faire un potager</h4>
       <div class="banner-content">
        <a href="/lands" class="btn-treehouse btn-sm">Trouver un terrain !</a>
        <a href="lands/new" class="btn-treehouse btn-sm"">Louer votre terrain </a>
      </div>
    </div>
  </div>
  <div class="item">
   <%= image_tag "tente.jpeg" %>
   <div class="carousel-caption">
     <h1>AirLnP</h1>
     <h4>Trouver votre terrain pour camper</h4>
     <div class="banner-content">
      <a href="/lands" class="btn-treehouse btn-sm">Trouver un terrain !</a>
      <a href="lands/new" class="btn-treehouse btn-sm"">Louer votre terrain </a>
    </div>
  </div>
</div>

</div>
<!-- </div> -->
   <!--  <div class="col-xs-12 col-sm-offset-2 col-sm-8">
      <p>Trouver votre terrain pour un potager, un evenement, un stantionnement ou bien camper!</p>
    --> <!-- </div> -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Précédent</span>
    </a>

    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Suivant</span>
    </a>



  </div>
</div>
</div>

app/views/partials/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<div class="container">
  <div class="col-xs-12 col-sm-offset-2 col-sm-8">
    <div class="footer">
      <div class="footer-links">
        <a href="https://github.com/"><i class="fa fa-github"></i></a>
        <a href="https://www.instagram.com"><i class="fa fa-instagram"></i></a>
        <a href="https://fr-fr.facebook.com/"><i class="fa fa-facebook"></i></a>
        <a href="https://twitter.com"><i class="fa fa-twitter"></i></a>
        <a href="https://fr.linkedin.com"><i class="fa fa-linkedin"></i></a>
      </div>

      <div class="footer-copyright">
        Ce site respecte les  <i class="fa fa-tree"></i>
      </div>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo_airlnp.png", alt:"logo"%>
  </a>

  <!-- Barre centrale  -->
  <div class="search-bar">
    <%= form_tag lands_path, method: :get do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control",
      placeholder: "Trouver votre terrain"
      %>
      <% end %>
  </div>

    <!-- Right Navigation -->
   <!--  <div class="navbar-wagon-right hidden-xs hidden-sm">
      <a href="bookings" class="navbar-wagon-item navbar-wagon-link">Bookings</a>
    </div>
 -->
    <% if user_signed_in? %>
    <div class="navbar-wagon-right hidden-xs">
      <%= link_to 'log out', destroy_user_session_path, method: :delete, class:"navbar-wagon-item navbar-wagon-link" %>
    </div>
    <div class="navbar-wagon-right hidden-xs ">
      <%= link_to 'Update profile', edit_user_registration_path, method: :get, class:"navbar-wagon-item navbar-wagon-link" %>
    </div>
     <% else %>
    <div class="navbar-wagon-right hidden-xs ">
      <%= link_to'Login', new_user_session_path, class:"navbar-wagon-item navbar-wagon-link"%>
    </div>

  <% end %>

  <!-- Profile picture with dropdown list -->

  <div class="navbar-wagon-item">
    <div class="dropdown">
      <img src=<%= user_signed_in? && current_user.photo_url ? cl_image_path(current_user.photo) : image_path("unique-arbre-image.jpg") %> class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
      <!-- <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

        <li><a href="#"><%=link_to edit_user_registration_path %></a></li>
        <li><a href="#"><%=destroy_user_session_path %></a></li>
      </ul> -->
    </div>
  </div>
</div>
<!-- Dropdown appearing on mobile only -->
<div class="navbar-wagon-item hidden-md hidden-lg">
  <div class="dropdown">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <li><a href="bookings">Bookings</a></li>
    </ul>
  </div>
</div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-sm-offset-4 ">
      <%= simple_form_for [@booking, @review] do |f| %>

      <%= f.input :content, as: :text, placeholder: 'Your comment', input_html:{class:'my_input'}%>
      <%= f.input :rating, as: :integer, placeholder: '0-5', input_html:{class:'my_input'}%>
      <%= f.button :button, "Add a review", type: :submit, class: :'btn btn-treehouse btn-sm' %>
      <% end %>
    </div>
  </div>
</div>